{{- if not .Values.backend.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit.fullname" . }}-backend
  labels:
    {{- include "orbit.backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backend.secrets.secretKey }}
  SECRET_KEY: {{ .Values.backend.secrets.secretKey | b64enc | quote }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
